language: android

dist: trusty
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
before_install:
  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi
env:
  - BUILD_PR_BRANCH=true USE_FRAMEBUFFER=true
  - BUILD_PR_BRANCH=false USE_FRAMEBUFFER=true

matrix:
  allow_failures:
    - env: BUILD_PR_BRANCH=true USE_FRAMEBUFFER=true